// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-O1seHO4H_c67sYlVhMYJ7anLvaT2-hA',
    appId: '1:1035080532242:web:6ff94df9bdf77e6334b3cb',
    messagingSenderId: '1035080532242',
    projectId: 'read-unlock-app-2026-76de3',
    authDomain: 'read-unlock-app-2026-76de3.firebaseapp.com',
    storageBucket: 'read-unlock-app-2026-76de3.firebasestorage.app',
    measurementId: 'G-CMT5JVCLM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-1yW6mmca0L9Vvw28mUF9NZaL6SVj1U',
    appId: '1:1035080532242:android:d7c91ad98a93362334b3cb',
    messagingSenderId: '1035080532242',
    projectId: 'read-unlock-app-2026-76de3',
    storageBucket: 'read-unlock-app-2026-76de3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnT0cJoXi2zRkbmdxTUyngHhppjGaQtCg',
    appId: '1:1035080532242:ios:4008757f45e767c634b3cb',
    messagingSenderId: '1035080532242',
    projectId: 'read-unlock-app-2026-76de3',
    storageBucket: 'read-unlock-app-2026-76de3.firebasestorage.app',
    iosBundleId: 'com.example.readUnlockApp',
  );

}